### ISSUE TITLE
Tekst bevat ’[streamer 3]‘

### ISSUE THREAD

**Issue by sanmai-NL** [Werkgroep-Toetsen-Op-Afstand/Resultaten-Enquete-Examencommissies#11]
Zie onderwerp. Ik kon het verder zelf niet plaatsen of oplossen.

**Comment by ShKlinkenberg** [comment]
Dank voor het melden @sanmai-NL. Ik heb de tekst aangepast.

**Comment by ShKlinkenberg** [comment]
Dank Sander,

Ik heb het aangepast.

Hartelijke groet,
Sharon

From: Sander Maijers ***@***.***>
Date: Thursday, 1 July 2021 at 16:19
To: Werkgroep-Toetsen-Op-Afstand/Resultaten-Enquete-Examencommissies ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Werkgroep-Toetsen-Op-Afstand/Resultaten-Enquete-Examencommissies] Tekst bevat ’[streamer 3]‘ (#11)

Zie onderwerp. Ik kon het verder zelf niet plaatsen of oplossen.
